-- Excel
-- ="insert into legales_abogado (nombre,correo,telefono1,telefono2) values('"&A2&"','"&C2&"','"&D2&"','"&E2&"');"
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CARLA JAUREGUI','jaureguicarla@outlook.com','1530705757','4371-1007');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PAOLA VERÓNICA BLANCO STILE','dra_blancostile@yahoo.com.ar','1551759779','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIA DUBRA','mariadubra@hotmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LUIS MATIAS GOMEZ MATEOS','matiasgomezmateos@hotmail.com','1131037070','11-3103-7071');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('HORACIO CESAR MATEO','info@estudiomateo.net','42443746','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIA LAURA MORASSO','laumorasso@hotmail.com ','48166500','1144116227');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FERNANDO LUIS OCHOA','fernando@estudioochoa.com ','42547823','1160008920');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BARBATO, JULIÁN GABRIEL','Administracion@EstudioBSM.com','1123322821','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MIGUEL ALEJANDRO PARDO','dr.miguelpardo@hotmail.com','1151385731','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('HUMBERTO FERNANDO NICOLÁS CAJAL','estudiocajal-cuda@hotmail.com','1166368080','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CARBALLES JORGE EZEQUIEL','jecarballes@gmail.com','4624-1760','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SALERNO JUAN DAMIAN','damian_salerno@yahoo.com.ar','1141889100','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ANA LAURA SAVINO','info@estudiosavino.com.ar ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ESEQUIEL AGOSTINO','cm@baronperezrachel.com','57762200','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FERNANDO OSCAR BETTI SANCHEZ','','42533647','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIA OFELIA SANDES','QUIROGA-MERRIS2008@HOTMAIL.COM','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GUSTAVO LEONARDO TELLO','serviciosjuridicosoeste@gmail.com','20905711','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MYRIAN EDITH BARBATO','epetraccabarbato@gmail.com','43421397','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MIANI, MARTÍN SEBASTIÁN','martinmiani@hotmail.com','37502601','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('HERNAN ROBERTO SARRATEA','hsarratea@hotmail.com','49691232','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LORENA VANESA MASSACCES y HERNAN DIEGO CANULLAN','estudio@estudiocanullan.com.ar','2345517879','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('RUBEN ABEL MONASTERIO','rubenmonasterio@hotmail.com','1143723775','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BRIAN NICOLAS IMERITO','difrancesco@drossi.com.ar ','1567619513','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FATIMA LOPEZ VERDE','lopezverdeabogados@gmail.com ','1536621221','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LUDUEÑA FELIX NICOLAS','celedelsur@hotmail.com ','42996999','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PABLO JUAN JOSE GARRO','pablojjgarro@gmail.com ','32212574','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ISIDRO MARIA FAVERIO','mfaverio@faustinolopezyasoc.com.ar','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SAAVEDRA, GUSTAVO RAFAEL','estudiogrs@hotmail.com','1164061419','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LEANDRO MARTIN BERRETTA','Lmberretta@gmail.com','1153158150','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ALFONSO ARRECHEA','aah@estudioarrechea.com.ar ','1143719731','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LEONARDO JAVIER PÉREZ RACHEL','cm@baronperezrachel.com','1135806621','57762200');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SEBASTIÁN PABLO DOCAMPO','victoriarmci@faustinolopezyasoc.com.ar','4282-8262','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CRISTIAN JAVIER MURO','cm@baronperezrachel.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GIANNINOTO ALBERTO SALVATORE','gianninoto@prevenlex.com.ar','44822248','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BISSO DAMIAN LEANDRO','leandrobisso@hotmail.com ','1168799293','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SILVINA ALEJANDRA SALOMON','estudiosalomonyasociados@gmail.com','1144298426','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SEBASTIÁN PABLO DOCAMPO','docamposebastian@hotmail.com','46254263','1540471823');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GISELLE LUDMILA PANTUSO','estudiopantusoasociados@hotmail.com','1530703108','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MAURO ENZO PANETTA','panetta.mauro@gmail.com','48143432','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('NATALÍ CAROLINA GNAPPA Y PABLO MARTIN COLLETTI','natalignappa@hotmail.com.ar','43922955','42449823');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('EZEQUIEL SIBILIA','esibilia@sibseb.com','1139250173','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARTINEZ ROCIO BELEN','rociobelenmartinez1992@gmail.com ','1163763092','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BELEC MARCOS VICTOR','marcosbelec_03@hotmail.com','1126502610','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ROMINA ANYELEN RODRIGUEZ','romina.rodriguez10@gmail.com','1537859451','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('DIEGO MANUEL SAMPEDRO','diegomanuelsampedro@gmail.com','1131164242','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('DOLORES GONZÁLEZ FONTÁN','doloresgonzalezfontan@hotmail.com','11 46510432','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PORCOPIO FLORENCIA','florporcopio@gmail.com ','1160423262','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CLAUDIO GABRIEL MARQUEZ','claudiogabrielmarquez@gmail.com','1541861700','1521638996');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ANGÉLICA MARIEL COTTAFAVA','angelica.mariel.cottafava@gmail.com','1157377893','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FERNANDO NICOLAS PERRONE','estudioperronesampaolesi@gmail.com','20732701','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ESTEBAN HORACIO CARRERAS','ehcarreras@yahoo.com.ar','1152364915','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('EZEQUIEL ALFREDO PICALLO','ezequiel.picallo@hotmail.com','4384-6553','1520210258');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ROSLI CARAM PABLO GUILLERMO','secretaria@mrcabogados.com.ar','43824215','43824161');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BRUNO ZELENAY','maribefrende@gmail.com','43782050','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARTIN FEDERICO WICHMANN','mfw@galarzawichmann.com.ar','1134271888','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ALEJO MARTÍN ERNESTO CARRERAS LOBO','acl@carreraslobo.com','48120762','48111773');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ANA GISELA ARISTIMUÑO','anagisela.abogada@gmail.com','1550057303','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('AGUSTIN HERNAN CONDE','agustinconde@estudiocondetravierso.com','43284008','2204822426');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SILVINA VERÓNICA ARCARO','arcarosilvina@gmail.com','43710135','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CHRISTIAN ADRIÁN LANARO','christian.lanaro@lanaroyasoc.com.ar','1140220888','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('VILLAFAÑE BRIAN EZEQUIEL','estudioasesor_bev@hotmail.com','1560071144','1562081098');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CLAUDIO GUSTAVO ROSJANSKI','estudiocrabogados@hotmail.com','1151109688','52948450');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CARLOS ERNESTO DURAN','drcarlosduran@gmail.com','1149919518','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LUCAS DANEL D’INGIANNA','info@estudiocdp.com.ar','1143716020','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ALAN DENIS PINO','alandpino@hotmail.com','1159660448','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BERON JONATAN OSCAR','jonatanberon@hotmail.com','44822248','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIA JOSEFINA BURGUBURU','jb@jbabogados.com.ar','1562043903','43265724');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CARLOS MARIANO MILANI','estudiojurídicomilani@yahoo.com','46288446','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FERNANDEZ GLADYS MÓNICA ADRIANA','siniestrosadroguemf@gmail.com','42942809','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('OSMAR GARAY','estudiogaraytessio@gmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('HERNAN ANDRES NONI','hernannoni@hotmail.com ','1143713554','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JUAN IGNACIO DASCAL y JUAN MARTIN BARLASSINA','MARTINBARLASSINA@GMAIL.COM ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GIANNINOTO ALBERTO SALVATORE','gianninoto.alberto@hotmail.com','44822248','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PERILLO NICOLAS','avalconsultores.art@gmail.com','2215958940','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MEDRANO MOISÉS','estudiojuridico.medrano@live.com.ar','49779542','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CESTAC VILLARES JULIETA','julieta.cestac@gmail.com','1161629189','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PATRICIO EZEQUIEL GALLEGOS','estudiolabart1@gmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ERICA FERNANDA BOHL','ericabohl@hotmail.com ','1550943077','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ALEJANDRO JORGE LUIS FERNÁNDEZ','alejofer80@hotmail.com','1551616226','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LEONEL GUSTAVO GALARZA','lgg@galarzawichmann.com.ar','42240186','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PABLO DANIEL RIDELLA','pridella@rmaabogados.com.ar','1564697301','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FEDERICO MARTIN ALDERISIO','federicomalderisio@hotmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('IGNACIO FAURE','ignaciofaure@hotmail.com','1536157242','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SEBASTIAN MATIAS LEVI','estudiojollca2@gmail.com','43712224','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SEBASTIÁN A. BAILLOT','sebastian@estudiobaillot.com.ar ','1131186116','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CARLOS ALBERTO FLORES Y DANIEL MARTÍNEZ PRADO','dmartinezprado@estudiofloresyasoc.com.ar ','11 40245440','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('RICARDO LUIS FLORIO','ricardoluis.florio@gmail.com ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GABRIELA ALEJANDRA TAIBO','abrielataibo@estudio-taibo.com.ar','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LUCIANO CISCATO','damian@lopezbustamante.com.ar','52725575','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ROBERTO HERALDO FERNANDEZ','kyfabogados@hotmail.com','1534362087','42221661');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PEDRO MARTIN MIÑO','mbestudio@hotmail.com','1134690486','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LUNA YAMILA SOLEDAD','lycasociadosjuridicos@gmail.com ','1567248519','1560444734');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('AGUSTÍN KATZ','agustinkatz@fibertel.com.ar','47489813','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PATRICIA MÓNICA CASCO','casco.patriciam@gmail.com ','1562399129','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('EVE ISABEL VILLALBA','abogada.evev4811@gmail.com ','1121464785','1135681526');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LIMONTA MARCO ABEL','marlimonta@gmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MIGUEL AGUSTIN TALIERCIO','mataliercio@yahoo.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ANIBAL GUILLERMO ERAÑA','anibalguillermoerana@hotmail.com.ar','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('VANESA RODRIGUEZ','vanesarodriguezabogada@gmail.com','53786596','46514799');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BRENDA FERRARO','estudiojuridico.bferraro@gmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CLAUDIA LILIANA GUTIERREZ','claudiagutierrezabogada@gmail.com ','1136201167','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LEANDRO NICOLAS GAMALDI ORTIZ','drleandrogamaldi@gmail.com ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIANO JOSE DEL RIO','marianojdelrio@gmail.com','47484937','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('EVA SOLEDAD PETRONE','legalespym@gmail.com ','1540392742','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GOMEZ STEFANIA BELEN','estudioalbano@outlook ','1559555151','31138881');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LUIS MATIAS GOMEZ MATEOS','matiasgomezmateos@hotmail.com','1131037070','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('AGUSTIN HERNAN CONDE','doctora_mlfernandez@yahoo.com.ar','1563697205','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JUAN MANUEL CURUBETO','drcurubeto@hotmail.com','1567357575','2204853723');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('DAIANA ANABELLA FIGUEREDO','fgestudiointegral@outlook.com','1562484389','75156910');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GLADYS ESTER BILORUS','estudiojuridicoakbg@gmail.com ','11618188894','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FLAVIA LORENA MONCHO','draflaviamoncho@gmail.com','1563044087','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('DANIEL ALBERTO ROSSI','drossi@drossi.com.ar','46294963','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JORGE ALEJANDRO INSUA','grassi@estudioinsua.com.ar','43714130','1164703331');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CRISTIAN COLUCCI','ccolucci@colucciabogados.com.ar','1154010103','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('WALTER SEBASTIAN GONZALEZ','walters_gonzalez@hotmail.com','2204823851','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ARNAL LUCIANA ANDREA','lucianaarnal@estudioarnal.com.ar','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MATÍAS CHRISTIAN GARCÍA CLIMENT','matiasgarciacliment@gmail.com ','45452488','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JUAN MIGUEL BURDA','abogadosbgp@gmail.com ','60883164','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('EDUARDO MUJICA','abadymujica@gmail.com','43225671','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MATIAS OSVALDO PUGLIESE','Matiaspugliese@gmail.com','46288446','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LUCIANA ANDREA ARNAL','luciana_arnal@estudioarnal.com.ar ','1567619513','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MATIAS HERNAN AMOEDO','amoedomatias@gmail.com','43820105','1144936656');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('AMÉRICA YESICA DANIELA TEVEZ','americatevez@gmail.com ','1151817720','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('OLIVIERI FABIANA ROSALÍA','farooli@hotmail.com ','1558940084','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ALBERTO ZARATE','zaratealberto@live.com.ar','1553193006','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CRISTIAN ANDRES PARKES','jap@estudioparkes.com ','42445026','1555277190');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BRENDA FERRARO','estudiojuridico.bferraro@gmail.com ','42021030','42029078');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('HERNÁN DIEGO PÉREZ RACHEL','hperezrachel@baronperezrachel.com','1135806621','57762200');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JORGE WALTER PAMPIN','pampin34@gmail.com','46252000','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIA EMMA ROLDAN','vialegalcontable@hotmail.com ','1165251842','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JUAN CRUZ MASETTI','internoestudio@yahoo.com.ar','43725109','43731088');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CRISTIAN ALAN TINO','tinocristian@hotmail.com','1156994085','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('RAMIRO MENDEZ CASARIEGO','ramiro@mcvg.com.ar','53682730','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('EZEQUIEL DEL VALLE CELADA','celadae@hotmail.com ','1147478134','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JORGE ALBERTO MARTIN IRIGOYEN','abogados@irigoyenrossi.com.ar','56226007','56285311');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LORELEY ALDANA SLIPCHINSKY','loreley@ssabogados.com.ar','1565356344','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARCELO EZEQUIEL MELER','mmeler@rmaabogados.com.ar','111532049314','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ANTONIO GRECO','drantoniogreco@yahoo.com.ar','1140490749','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JAVIER ALBERTO MENGUAL','ejmengual@gmail.com ','42039745','1549983463');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('RIVAS AGUSTÍN SEBASTIÁN','rivas.as@hotmail.com','45197467','1536040400');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LUCAS DANEL D’INGIANNA','info@estudiocdp.com.ar','1143716020','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BERENGUER FERNANDO CESAR','fernandoberenguer@cpacf.org.ar','1544040479','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JUAN MANUEL CURUBETO','drcurubeto@hotmail.com','2204853723','1567357575');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('BLAS CAPRA','blascapra.estudio@gmail.com ','2215739494','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MILANI CARLOS MARIANO','estudiojurídicomilani@yahoo.com.ar','46288446','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MONTERO, CLAUDIA EMMA','estudio.molina.montero@gmail.com','42938515','42141293');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SANTIAGO RODOLFO ALLEN','carpetasallen@gmail.com ','1158010175','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIANA DI FABIO','difabiomariana4@gmail.com','1154755551','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SERGIO ANGEL FUCCI','estudiofucci@hotmail.com ','1157928667','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIA OFELIA SANDES QUIROGA','MERRIS2008@HOTMAIL.COM','1540957590','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('EDUARDO EZEQUIEL ARBETMAN','eduardoarbetman@hotmail.com','42440741','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('RUBÉN FACUNDO BEVERAGGI','rbeveraggi@gmail.com','42026696','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FACUNDO EZEQUIEL OLAZAR','folazar@cpacf.org.ar ','1560492769','1143713645');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MATIAS OSVALDO POSCA','matiasposca@estudioposca.com.ar','1143730205','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PONCE PABLO MARTIN, Y MARÍA EUGENIA LUPI SERRES','raffolupi.provincia@gmail.com, ','1523689812','1544932492');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('AGUSTIN OSCAR MAS','mas.agustin@gmail.com ','1533403479','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CABEZAS SILVANA NOEMI y FERNANDEZ PALAVECINO CARLOS ARIEL','dracabezassilvana@gmail.com','1155259672','1123293309');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MOIRA FLORENCIA PUEBLA WALLACE','estudio@wmabogados.com ','52638974','52638973');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GUSTAVO FEDERICO FARCHOLA','farcholag@hotmail.com ','42251509','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SERGIO ANGEL FUCCI Y MARIELA ROXANA SPADACCINI','estudiofucci@hotmail.co','1157928667','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CINTIA GISELA CARRANZA','carranza@cabogados.com.ar','41239060','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GUIDO KARP','karp@guidokarp.com.ar','52194802','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARTINA INES MATEO','martinamateo@estudiomateo.com.ar ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MIGUEL ANGEL PONTORIERO','mpontoriero@live.com.ar','47859996','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JUAN PABLO FERNANDEZ','estudiofernandezlusero@hotmail.com ','1553839461','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MELINA MARGOT CANZIANI','cnatc301@hotmail.com','1133830434','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ADRIAN MAURICIO PONTECORVO','adrianpontecorvo@yahoo.com.ar','1159380258','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ROSSI ADRIAN FLOREAL','estudio@afrossi.com.ar','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MYRIAM NOEMÍ SZPYTMA','myriamszpytma@hotmail.com ','47320181','47439463');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PEREZ FEDERICO LEONEL','fperez@perezyasoc.com.ar','1535433016','52524800');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIANO GURRIERI','estudiomarianogurrieri@gmail.com','1135545642','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JUAN CRUZ MASETTI','internoestudio@yahoo.com.ar','1127212743','1125145999');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('HERNAN ALBERTO TEJERO','hernantejero@gmail.com ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIANA GRICELDA CALABRIA','calabria.mariana@hotmail.com ','1535192299','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ZUNINO NATALIA JESICA','zblegales@gmail.com','1563073141','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('IGNACIO FRESNO APARICIO','ifresnoaparicio@gmail.com','52390505','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARÍA DE LAS MERCEDES ALVAREZ','dramercedesalvarez2014@gmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ARTEMIO GERMAN ROLANDO','artemiorolando@rcasociados.com.ar','58111953','1163758404');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PABLO DANIEL RIDELLA','pridella@rmaabogados.com.ar','1564697301','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ALDO ARIEL CABALLERO MARTINEZ','ccmlegales@gmail.com ','01115 23963550','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('EMILIANO FABIÁN ALLORO','alloro.emiliano@gmail.com','1560155620','1120829632');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SALERNO JUAN DAMIAN','damian_salerno@yahoo.com.ar ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JUAN PATRICIO RAFFO','jpraffo8@gmail.com','70790707','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('DIEGO ARIEL CASTRO VYLANYK','castrodiego.legales@gmail.com ','1160475944','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARÍA AURELIA CARI DECHAT','estudiocgz@gmail.com','47047395','1567318383');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GOMEZ GAUNA MARCOS MARCELO','march_18_702@hotmail.com ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GUILLERMO MARIANO CHAMBERS','chambersgm@hotmail.com','1143429154','1143429147');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MAXIMILIANO ALEXIS PAZ','mcoppa@estudiomazzolatti.com.ar','1565779440','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('JOSE LUIS TORRANDEL','jlt@estudiotorrandel.com.ar','43735530','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('HECTOR NORBERTO CEREZO','hncerezo@hotmail.com ','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CINTIA ALEJANDRA SANCHEZ','cintia.a.sanchez@hotmail.com','44510078','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ROMINA ADRIANA FERNANDEZ','rfestudiojuridico1@gmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CABRAL JOSE RICARDO','cabraljosericardo@live.com.ar ','1167073175','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('VERÓNICA SOLEDAD VESCIO','veronica@estudioiralevescio.com ','1140824761','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('DANIEL ALEJANDRO RICO','dr@abogadosdeart.com.ar','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PEDRIDO NOELIA VILDA','ATQMN@YAHOO.COM.AR ','1134551985','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARISOL VAZQUEZ','estudiovv@hotmail.com','6593335','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CARINA ROXANA ROSA','carinaroxanarosa@yahoo.com.ar','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PEDRIDO NOELIA','VILDA.ATQMN@YAHOO.COM.AR','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('NAHUEL IVAN FONSECA','legalesnf@gmail.com','1165198660','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CONSTANZA NATALI MURDOCCA','nmurdocca@hotmail.com','153653254','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CARRIZO MÓNICA CARINA','monica54carina@yahoo.com.ar','1564801576','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GABRIELA RAMIREZ GONZALEZ','ramirezgonzalez@hotmail.com','1165424120','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SARAVIA MIGUEL ANGEL','saraviaangel87@gmail.com','','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ANDREA LORENA PETRONE','estudiopetrone22@gmail.com ','1566815617','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GUSTAVO FEDERICO FARCHOLA','farcholag@hotmail.com ','4225-1509','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FLORENCIA SOFIA HULLMAN DIESER','dra.hullmandieser@gmail.com','1134145037','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('PAOLA ELISABETH GONZALEZ','estudiodragonzalez@live.com.ar','1163044346','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('SANCHEZ ARTURO FABIAN','estudiosanchezyasociados@yahoo.com','1557133440','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LEANDRO MARTIN BERRETTA','Lmberretta@gmail.com','1153158150','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('INGRID VANESA MUÑOZ','dra.munozingrid@gmail.com','1165242086','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('FERNANDEZ MARIANO GERMAN','fernandezmarianog@gmail.com','1558716175','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARTIN DARIO ARANDA','arandam_81@hotmail.com','1142479731','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ELIANA SOLEDAD SUSPERREGUI','elianass_15@yahoo.com.ar ','1524112848','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GYALAY LEANDRO NICOLAS','GYALAYLEANDRO@HOTMAIL.COM','1124522206','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('VANESA PITTARO','damian@lopezbustamante.com.ar','5112725575','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CARLOS ALBERTO AGUIN','aguinrodriguez@ciudad.com.ar','aguin_carlos@yahoo.com.ar','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MATIAS DOMINGUEZ','dominguez_estudiojuridico@hotmail.com','1144752431','1121493287');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('VANESA PITTARO','damian@lopezbustamante.com.ar','1152725575','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LAURA LUCRECIA RABILOTTA','info@estudiorobilotta.com.ar','1142949679','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('GUILLERMO MARTIN CHAIMAN','gchaiman@cpacf.org.ar ','1158432195','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIANA VERÓNICA SALOMÓN','mavesalomon@hotmail.com','1557244147','1143717314');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIA SOLEDAD TABUCCHI','mstabucchi@faustinolopezyasoc.com.ar','1143828262','114381353');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('DIEGO SOSA','info@cabralabogados.com.ar ','11 48040670','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CECILIA ANDREA SKRAGA','cecilia.skraga@gmail.com','11-3108-6090','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('CAROLINA ELIANA PUCCI','carolinapucci@gmail.com','116150-7457','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ALTIMARI SILVIA ALEJANDRA','altimarisilvia@hotmail.com','1567589279','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('ALDO RUBEN ROMERO','aldorromero@hotmail.com','1137323295','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('MARIA VICTORIA GIMENEZ','victoria_gim@hotmail.com ','1162643293','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LILIANA ALICIA NIEVA','liliananiev57@gmail.com','1150539051','');
insert into legales_abogado (nombre,correo,telefono1,telefono2) values('LOPEZ RICARDO FAUSTINO','victoriarmci@faustinolopezyasoc.com.ar','1142828262','');

