insert into legales_excepcion (nombre) values('EXCEPCION DE PAGO');
insert into legales_excepcion (nombre) values('EXCEPCION DE INCOMPETENCIA POR DAÑO PSICOLOGICO');
insert into legales_excepcion (nombre) values('EXCEPCION DE FALTA DE LEGITIMACION PASIVA');
insert into legales_excepcion (nombre) values('EXCEPCION DE COSA JUZGADA ADMINISTRATIVA');
insert into legales_excepcion (nombre) values('EXCEPCION DE INCOMPETENCIA MATERIAL POR LESION NO RECLAMADA EN SRT');
insert into legales_excepcion (nombre) values('EXCEPCION DE NO SEGURO');
insert into legales_excepcion (nombre) values('EXCEPCION DE INCOMPETENCIA TERRITORIAL');
insert into legales_excepcion (nombre) values('EXCEPCION DE INCOMPETENCIA MATERIAL');
insert into legales_excepcion (nombre) values('EXCEPCION DE FALTA DE LEGITIMACION ACTIVA');
insert into legales_excepcion (nombre) values('EXCEPCION DE PRESCRIPCION');
insert into legales_excepcion (nombre) values('ACUMULACION DE CAUSAS');
insert into legales_excepcion (nombre) values('EXCEPCION DE COSA JUZGADA');