insert into legales_jurisdiccion  (nombre) values('LA MATANZA');
insert into legales_jurisdiccion  (nombre) values('SAN MARTIN');
insert into legales_jurisdiccion  (nombre) values('AVELLANEDA');
insert into legales_jurisdiccion  (nombre) values('QUILMES');
insert into legales_jurisdiccion  (nombre) values('MORON');
insert into legales_jurisdiccion  (nombre) values('LOMAS DE ZAMORA');
insert into legales_jurisdiccion  (nombre) values('SAN MIGUEL');
insert into legales_jurisdiccion  (nombre) values('LANUS');
insert into legales_jurisdiccion  (nombre) values('SAN ISIDRO');
insert into legales_jurisdiccion  (nombre) values('MORENO');
