# Generated by Django 4.2.6 on 2023-10-18 03:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('correo', models.CharField(max_length=120, null=True)),
                ('telefono1', models.CharField(max_length=20, null=True)),
                ('telefono2', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonoJus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoNegociacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProcesal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Excepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionPericia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionPMP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Causa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_derivacion', models.DateTimeField()),
                ('asunto', models.IntegerField()),
                ('caratula', models.CharField(max_length=280)),
                ('cod_17039', models.CharField(max_length=40)),
                ('tribunal', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('fecha_inicio_demanda', models.DateTimeField()),
                ('incapacidad_reclamada', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reclama_dano_sicologico', models.BooleanField(default=False)),
                ('monto_demanda', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_pmi', models.DateTimeField()),
                ('porcentaje_srt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_jus', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monto_bono', models.DecimalField(decimal_places=2, max_digits=14)),
                ('detalle', models.CharField(blank=True, max_length=280, null=True)),
                ('preexistencia', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('negociable_pmo', models.BooleanField(default=False)),
                ('negociable_pmp', models.BooleanField(default=False)),
                ('fecha_pedido_pmp', models.DateTimeField()),
                ('fecha_asigno_pmp', models.DateTimeField()),
                ('fecha_pmp', models.DateTimeField()),
                ('porcentaje_pmp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_autorizado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ofrecimiento', models.DecimalField(decimal_places=2, max_digits=14)),
                ('contra_oferta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_ultimo_ofrecimiento', models.DateTimeField()),
                ('monto_acuerdo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_presentacion_acuerdo', models.DateTimeField()),
                ('hay_cbu', models.BooleanField(default=False)),
                ('homologado', models.BooleanField(default=False)),
                ('fecha_pedido_fondos', models.DateTimeField()),
                ('fecha_venci_pago', models.DateTimeField()),
                ('observacion', models.CharField(blank=True, max_length=120, null=True)),
                ('ppmed', models.CharField(blank=True, max_length=60, null=True)),
                ('ppsic', models.CharField(blank=True, max_length=60, null=True)),
                ('pcont', models.CharField(blank=True, max_length=60, null=True)),
                ('oficios', models.CharField(blank=True, max_length=60, null=True)),
                ('confesional', models.BooleanField(default=False)),
                ('testimonial', models.BooleanField(default=False)),
                ('otras_pruebas', models.CharField(blank=True, max_length=60, null=True)),
                ('sentencia', models.CharField(blank=True, max_length=60, null=True)),
                ('pedido_fondos', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_facturado', models.DateTimeField()),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.abogado')),
                ('bono_y_jus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.bonojus')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.company')),
                ('esatdo_negociacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.estadonegociacion')),
                ('estado_procesal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legales.estadoprocesal')),
                ('excepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legales.excepcion')),
                ('jurisdiccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.jurisdiccion')),
            ],
        ),
    ]
