# Generated by Django 4.2.6 on 2023-10-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='fecha_asigno_pmp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_derivacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_facturado',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_inicio_demanda',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_pedido_fondos',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_pedido_pmp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_pmi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_pmp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_presentacion_acuerdo',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_ultimo_ofrecimiento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_venci_pago',
            field=models.DateField(),
        ),
    ]
