# Generated by Django 4.2.6 on 2023-10-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0002_alter_causa_fecha_asigno_pmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='correo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='telefono1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='abogado',
            name='telefono2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
