# Generated by Django 4.2.6 on 2023-10-23 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0003_alter_abogado_correo_alter_abogado_telefono1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='causa',
            old_name='cod_17039',
            new_name='expediente',
        ),
        migrations.AlterField(
            model_name='causa',
            name='oficios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legales.oficio'),
        ),
    ]
