# Generated by Django 4.2.6 on 2023-10-23 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0004_oficio_rename_cod_17039_causa_expediente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='causa',
            name='lesiones_reclamada',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='causa',
            name='tipo_proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legales.tipoproceso'),
        ),
    ]
