# Generated by Django 4.2.6 on 2023-10-23 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0005_tipoproceso_causa_lesiones_reclamada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='tipo_proceso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='legales.tipoproceso'),
            preserve_default=False,
        ),
    ]
