# Generated by Django 4.2.6 on 2023-10-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0006_alter_causa_tipo_proceso'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVencimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vencimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.causa')),
                ('tipoVencimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.tipovencimiento')),
            ],
        ),
    ]
