# Generated by Django 4.2.6 on 2023-10-24 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0007_tipovencimiento_vencimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vencimiento',
            old_name='cause',
            new_name='causa',
        ),
    ]
