# Generated by Django 4.2.6 on 2023-10-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0008_rename_cause_vencimiento_causa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='causa',
            old_name='esatdo_negociacion',
            new_name='estado_negociacion',
        ),
        migrations.AddField(
            model_name='causa',
            name='observacion_pericia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='vencimiento',
            name='fecha',
            field=models.DateField(),
        ),
    ]
