# Generated by Django 4.2.6 on 2023-10-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0010_alter_causa_incapacidad_reclamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='monto_demanda',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True),
        ),
    ]
