# Generated by Django 4.2.6 on 2023-10-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0012_alter_causa_monto_bono_alter_causa_monto_jus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='preexistencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
