# Generated by Django 4.2.6 on 2023-10-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0014_alter_causa_contra_oferta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='fecha_facturado',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_pedido_fondos',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='fecha_venci_pago',
            field=models.DateField(null=True),
        ),
    ]
