# Generated by Django 4.2.6 on 2023-10-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0017_alter_causa_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abogado',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='bonojus',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='estadonegociacion',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='estadoprocesal',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='excepcion',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='jurisdiccion',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='observacionpericia',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='observacionpmp',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='oficio',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='tipoproceso',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='tipovencimiento',
            unique_together={('nombre',)},
        ),
        migrations.AlterUniqueTogether(
            name='vencimiento',
            unique_together={('fecha', 'causa', 'tipoVencimiento')},
        ),
    ]
