# Generated by Django 4.2.6 on 2023-10-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0018_alter_abogado_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='fecha_presentacion_acuerdo',
            field=models.DateField(null=True),
        ),
    ]
