# Generated by Django 4.2.6 on 2023-10-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0021_alter_causa_fecha_asigno_pmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='porcentaje_pmp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
