# Generated by Django 4.2.6 on 2023-10-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0022_alter_causa_porcentaje_pmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='estado_negociacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='legales.estadonegociacion'),
        ),
    ]
