# Generated by Django 4.2.6 on 2023-10-26 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0025_alter_abogado_telefono1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='causa',
            name='excepcion',
        ),
        migrations.CreateModel(
            name='ExcepcionCausa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.causa')),
                ('excepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legales.excepcion')),
            ],
            options={
                'unique_together': {('causa', 'excepcion')},
            },
        ),
    ]
