# Generated by Django 4.2.6 on 2023-10-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0027_alter_causa_fecha_pmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='reclama_dano_sicologico',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
