# Generated by Django 4.2.6 on 2023-10-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0028_alter_causa_reclama_dano_sicologico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='negociable_pmo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='negociable_pmp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
