# Generated by Django 4.2.6 on 2023-10-26 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0029_alter_causa_negociable_pmo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='lesiones_reclamada',
            field=models.CharField(blank=True, max_length=380, null=True),
        ),
    ]
