# Generated by Django 4.2.6 on 2023-10-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0030_alter_causa_lesiones_reclamada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='fecha_inicio_demanda',
            field=models.DateField(null=True),
        ),
    ]
