# Generated by Django 4.2.6 on 2023-10-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0032_alter_causa_fecha_asigno_pmp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causa',
            name='contra_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='incapacidad_reclamada',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='monto_acuerdo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='monto_autorizado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='monto_bono',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='monto_demanda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='monto_jus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='ofrecimiento',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='porcentaje_pmp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='porcentaje_srt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='causa',
            name='preexistencia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14, null=True),
        ),
    ]
