# Generated by Django 4.2.6 on 2023-11-14 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legales', '0034_remove_causa_oficios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Oficio',
        ),
    ]
